#!/usr/bin/sh
opt=$1

print(){
if [ "$opt" = "-s" ] || [ "$opt" = "-sd" ] || [ "$opt" = "-ds" ]; then
espeak -ven+f3 -p20 -k20 -s160 -a70 "$1" 2>/dev/null
fi
if [ "$opt" = "-d" ] || [ "$opt" = "-sd" ] || [ "$opt" = "-ds" ]; then
echo $1
fi
}

sound(){
if [ "$opt" = "-s" ] || [ "$opt" = "-sd" ] || [ "$opt" = "-ds" ]; then
espeak -ven+f3 -p20 -k20 -s160 -a70 "$1" 2>/dev/null
fi
}
if [ "$opt" = "-s" ] || [ "$opt" = "-sd" ] || [ "$opt" = "-ds" ]; then
sudo apt-get install python-dev
sudo apt-get install espeak python-espeak
fi
sound "Hi. this is espeak engine. today we going to install the website change detection tool. Firstly we need to update and upgrade."
sudo apt update && sudo apt upgrade
sound "System has been succesfully upgraded. Now we install Docker Composite."
sudo chmod +x *
sound "To install correct Docker. Enter your system Architecture correctly 32 or 64."
./InstallDockerComp.sh
sound "Docker Composite is successfully installed. Initiating the Y M L Creation."
./CreateYML.sh
cd ~/changedetection
echo "else leave it as it is."
sudo docker-compose up -d
sound "Docker Composite is up and running. If there has no changes done on the Default port number then try opening the generated link."
ipad=$(hostname -I | cut -f1 -d' ')
clear
echo "<<   http://$ipad:5000   >>"

soung "if you are facing any errors send a message to my email."
echo " "
echo " "
echo "Email address : yalavarthisreeman21725@gmail.com"
